import type { FeedVideo } from './types';

// Demo content for design review before the staging backend is wired.
// Public HLS test streams stand in for Cloudflare Stream playback URLs.
export const MOCK_FEED: FeedVideo[] = [
  {
    id: 'demo-1',
    artistId: 'demo-artist-1',
    artistName: 'Nova Ray',
    artistHandle: 'novaray',
    artistAvatarUrl: null,
    title: 'Midnight Static',
    genreSlug: 'electronic',
    playbackUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    thumbnailUrl: 'https://picsum.photos/seed/herd1/720/1280',
    durationSeconds: 96,
    heartCount: 1204,
    score: 12.4,
  },
  {
    id: 'demo-2',
    artistId: 'demo-artist-2',
    artistName: 'The Hollow Pines',
    artistHandle: 'hollowpines',
    artistAvatarUrl: null,
    title: 'Gravel Road',
    genreSlug: 'country',
    playbackUrl:
      'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    thumbnailUrl: 'https://picsum.photos/seed/herd2/720/1280',
    durationSeconds: 148,
    heartCount: 864,
    score: 9.1,
  },
  {
    id: 'demo-3',
    artistId: 'demo-artist-3',
    artistName: 'Juno V',
    artistHandle: 'junov',
    artistAvatarUrl: null,
    title: 'Backseat Confessions',
    genreSlug: 'rnb',
    playbackUrl:
      'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8',
    thumbnailUrl: 'https://picsum.photos/seed/herd3/720/1280',
    durationSeconds: 132,
    heartCount: 2211,
    score: 18.7,
  },
  {
    id: 'demo-4',
    artistId: 'demo-artist-1',
    artistName: 'Nova Ray',
    artistHandle: 'novaray',
    artistAvatarUrl: null,
    title: 'Neon Communion',
    genreSlug: 'electronic',
    playbackUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    thumbnailUrl: 'https://picsum.photos/seed/herd4/720/1280',
    durationSeconds: 110,
    heartCount: 493,
    score: 6.2,
  },
  {
    id: 'demo-5',
    artistId: 'demo-artist-4',
    artistName: 'Sol Marín',
    artistHandle: 'solmarin',
    artistAvatarUrl: null,
    title: 'Baila Conmigo',
    genreSlug: 'latin',
    playbackUrl:
      'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    thumbnailUrl: 'https://picsum.photos/seed/herd5/720/1280',
    durationSeconds: 121,
    heartCount: 1580,
    score: 14.3,
  },
  {
    id: 'demo-6',
    artistId: 'demo-artist-5',
    artistName: 'Paper Crowns',
    artistHandle: 'papercrowns',
    artistAvatarUrl: null,
    title: 'Basement Tapes',
    genreSlug: 'rock',
    playbackUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    thumbnailUrl: 'https://picsum.photos/seed/herd6/720/1280',
    durationSeconds: 104,
    heartCount: 322,
    score: 4.8,
  },
];
